baseURL = '/'
languageCode = 'en'
defaultContentLanguage = "en"
hasCJKLanguage = true
title = 'Apple Newsroom'
copyright = 'Floyd Li'
theme = 'hugo-theme-itheme'
paginate = 5
[params]
  defaultCover = 'https://www.apple.com.cn/newsroom/images/apple-logo_black.jpg.landing-regular_2x.jpg'
  email = 'floyd.li@outlook.com'
  [[params.socialMedia]]
    name = 'Github'
    url = 'https://github.com/floyd-li'
  [[params.socialMedia]]
    name = 'Twitter'
    url = 'https://twitter.com/some-one'
  [[params.blogroll]]
    name = '驭风笔记'
    url = 'https://yufengbiji.com/'
  [[params.blogroll]]
    name = 'Apple'
    url = 'https://apple.com/'
